### ISSUE TITLE
Error at config.json

### ISSUE THREAD

**Issue by Rain0830** [peterhanania/Pogy-Old#14]
![Screenshot_20210718-034456](https://user-images.githubusercontent.com/77835007/126047897-e2b60872-ff37-40bc-998f-626183ccc0ea.jpg)
The config.json has so many errors

**Comment by ConnorDoesDev** [comment]
lmao, that's because JSON doesn't support comments. However, the comments are there to tell you what you should put in the config.json file.

**Comment by ConnorDoesDev** [comment]
Close this.

**Comment by AhmadShkour71** [comment]
Delete **//** and any words after slash
