### ISSUE TITLE
Syntaxerror

### ISSUE THREAD

**Issue by sagnikoni** [peterhanania/Pogy-Old#15]
![Screenshot_2021-07-18-02-23-32-015_com.android.chrome.jpg](https://user-images.githubusercontent.com/72556320/126048581-abf80326-294c-4a3b-9492-12ec12af86a6.jpg)

**Comment by sagnikoni** [comment]
How to fix?

**Comment by eNtee-bots** [comment]
bro please read the error thats how to fix :/

Unexpected token / in JSON at position 44

**Comment by progamer68** [comment]
Don't use Node.js version v12. Use node 14.x or higher.

**Comment by ConnorDoesDev** [comment]
> Don't use Node.js version v12. Use node 14.x or higher, or you might have done something wrong in config.json. Please see to it that your `config.json` has no errors and is in the JSON file format.

No, just no.

**Comment by AhmadShkour71** [comment]
Delete **//**  and any words after slash
