### ISSUE TITLE
Dashboard is broken

### ISSUE THREAD

**Issue by xX-Joni-Xx** [peterhanania/Pogy-Old#20]
The Dashboard isnt loading everything right. Please update and fix this

![grafik](https://user-images.githubusercontent.com/76492858/132224871-e67f2b45-6560-4c45-a3f8-3bd0fbcb2303.png)
![grafik](https://user-images.githubusercontent.com/76492858/132224914-2ba0d825-8e20-4f0e-b6a2-0c056c954dd6.png)
![grafik](https://user-images.githubusercontent.com/76492858/132224944-fc11ed24-e774-48f2-b78c-eeaa49d412d0.png)

**Comment by ConnorDoesDev** [comment]
It's not broken. It's just you. Fix your CSS file path.

**Comment by xX-Joni-Xx** [comment]
How?

**Comment by xX-Joni-Xx** [comment]
This `if (fullUrl == domain || fullUrl == `${domain}/style.css` || fullUrl == `${domain}/style.css` || fullUrl == `${domain}/favico.ico` )` ? If yes how? I am not good with CSS

**Comment by xX-Joni-Xx** [comment]
Fixed it

**Comment by xX-Joni-Xx** [comment]
```if (fullUrl == domain || fullUrl == `${domain}/css/style.css` || fullUrl == `${domain}/css/style.css` || fullUrl == `${domain}/favico.ico` )```
