### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by GalackQSM** [peterhanania/Pogy-Old#22]
Hello,
is this error dangerous?

![0p4gb5f](https://user-images.githubusercontent.com/44106790/132376349-74903236-e845-48d2-a24e-f8321b0d5bf0.png)

**Comment by AhmadShkour71** [comment]
he tell you Unknown webhook
Check yours webhook clinet and he tell you other error displayAvatarURL is null 
in file (message reaction add)
