### ISSUE TITLE
The Stats site is showing wrong Stats

### ISSUE THREAD

**Issue by xX-Joni-Xx** [peterhanania/Pogy-Old#23]
The Stats page is showing the bot stats from your public bot when i am selfhosting the bot.

![grafik](https://user-images.githubusercontent.com/76492858/132651589-76306c88-b95e-4cb9-8b32-3c1b4c4b2ff9.png)

**Comment by ConnorDoesDev** [comment]
Ofcourse, because the iFrame is still linking to it's DataDog page. Just modify it.

**Comment by xX-Joni-Xx** [comment]
How? And what do i have to change?

**Comment by ConnorDoesDev** [comment]
It's simple, you do know you need some experience with basic dir tracks, right? <main directory> -> dashboard -> templates -> stats.ejs

Then, do as you wish.

**Comment by xX-Joni-Xx** [comment]
I know the path but how can i reset the datas?

**Comment by AhmadShkour71** [comment]
you need go dashbord data fog snd made panels ...etc and copy url project and input in status file but you need experience to data dog

**Comment by AndyIshereBoi** [comment]
@AhmadShkour71 u should make it easier in v2 to have that info and a tutorial of how to do it
