### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [peterhanania/Pogy-Old#24]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by eNtee-bots** [comment]
Hey you can contact peter per Discord DM or Discord Support Server:

Discord Tag: Peter_#4444
Support Server: https://discord.com/invite/FqdH4sfKBg

**Comment by AhmadShkour71** [comment]
Hi Jamie
Iam, Support in Pogy 
iam will tell petter for that
Thx for tell us

**Comment by peterhanania** [comment]
Hello, 
Thank you for bringing this to my attention.
I currently do not have an email I can leave publicly as you can always contact me via Discord as mentioned above. 
If you do not have the platform, do you mind writing your issue here?

**Comment by AhmadShkour71** [comment]
@JamieSlome close pls
