### ISSUE TITLE
Dashboard CSS Broken & OAuth2 won't work.

### ISSUE THREAD

**Issue by rodrigoricky** [peterhanania/Pogy-Old#25]
Dashboard CSS Broken & OAuth2 won't work. I follow the tutorial and followed the previous solution to closed issues here, still, doesn't work.

**Comment by ConnorDoesDev** [comment]
The CSS + OAuth both is working perfectly fine. It's a you issue.

**Comment by rodrigoricky** [comment]
How do I fix it?

**Comment by AhmadShkour71** [comment]
join the support server and go to support room and see pins


for problem broken css ; pogy is fine but if use localhost dashboard not show good


support pogy : https://discord.gg/vwQuF864
