### ISSUE TITLE
Will there come a new Version from Pogy?

### ISSUE THREAD

**Issue by JoniXTech** [peterhanania/Pogy-Old#26]
Will there come a new Version from Pogy or a other Bot like Pogy?

I love Pogy but it is using an old Discord.js Version

**Comment by AhmadShkour71** [comment]
From Owner Pogy **Petter**

![Screenshot_20210925-130822_Discord.jpg](https://user-images.githubusercontent.com/73717039/134767651-6588be5e-4f43-45bf-9f82-32434f52d73a.jpg)
