### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by numarkpro** [peterhanania/Pogy-Old#32]
![image](https://user-images.githubusercontent.com/73024472/139849342-b0d72a06-8197-42ee-9aea-ba839a9fc8be.png)

Where change this massege?

**Comment by ConnorDoesDev** [comment]
Change it in the logger file.

**Comment by numarkpro** [comment]
Can you give directory?

**Comment by AhmadShkour71** [comment]
search to bot status and disable 
ez

**Comment by loom4k** [comment]
It's probably in root/utils/logger.js
